### ISSUE TITLE
How to define which display is "screen 1" and which "screen 2"

### ISSUE THREAD

**Issue by nauta** [ianyh/Amethyst#1131]
Using Amethyst v0.15.4 (91) on MacOS Big Sur, and working with an external monitor.

With most external monitors, throwing windows (⇧⌃⌥  + 1/2) to "Screen 1" → internal macbook screen and to "Screen 2" → external monitor. 
But with some other external monitors (office with flexible workspaces), these are switched: "Screen 1" → external monitor and "Screen 2" → internal macbook screen.

Is there some way I can define/change these screen settings, and set "Screen 1" to always default to my internal screen? I already tried dragging the menu bar in the Display : Arrangement preferences, but that didn't work.

**Comment by CourteousCoder** [comment]
I think it hooks into macOS's Display Preferences. I think this is also the case for setting the "main" screen. I was able to change the main screen by going to `System Preferences` -> `Displays` -> `Arrangement` and then drag-and-dropping the "title bar" from one display to another. The display with the title bar seems to be the "main" display with `meta+M`. 

Because of this observation, I think Amethyst is determining which display is "Screen 1" (or "Screen 2", etc) from the system's display index. I only have one external display, so I cannot confirm my hypothesis. If my hypothesis is correct, then perhaps unplugging the displays, and reconnecting them in the correct order (or finding a way to programmatically re-index the displays at the OS-level) might help you. 

If you find the solution, please share it because I am sure others are curious too.

![image](https://user-images.githubusercontent.com/10914070/133134302-b6b8f77a-bcd1-454d-9665-6e3e1c800633.png)

**Comment by LoneFireBlossom** [comment]
I have the same question.
I use iPad sidecar:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/50087596/156915660-6d5aa731-1d3d-4114-a7f5-14cfd598508f.png">

And internal macbook screen is "monitor 1":
<img width="495" alt="image" src="https://user-images.githubusercontent.com/50087596/156915689-91a4453d-5509-404a-8dca-249443deb8ec.png">

but when I use Amethyst shortcut "throw focused window to screen 1", window on internal macbook screen will be moved to iPad sidecar screen.
When I use "throw focused window to screen 2", window on iPad sidecar screen will be moved to internal macbook screen.

Monterey 12.3 Beta (21E5227a)

**Comment by ianyh** [comment]
Screens are sorted horizontally on the x-axis. The actual labels are uuids and do not lend themselves well to shortcuts.
