### ISSUE TITLE
Need to press keyboard shortcut twice to get it to work

### ISSUE THREAD

**Issue by HanSooloo** [ianyh/Amethyst#1161]
Can't recall when it started happening .. maybe in the last 2~3 weeks.  It could also have coincided with my macOS Monterey update.

Every time I want to move a window to a different screen or different space, I have to press the shortcut keys _twice_.  I only had to press once before.

**Comment by pdgessler** [comment]
Same problem here. For me, it does seem to have started when I updated to macOS Monterey yesterday morning. It looks like the first press of the keyboard shortcut retiles the background windows but does not throw the foreground (focused) window to the new space. The second press of the keyboard shortcut does successfully throw the window. 

I am (and had been prior to this problem occurring) using Opt+Shift+_n_ for the keyboard shortcut for throwing windows to space _n_, in case that is relevant.

I also tried both enable and disable for the General preference "Follow thrown windows between spaces" to see if that had any impact, but two presses of the keyboard shortcut are required in both situations.

**Comment by fedragon** [comment]
It definitely started after the update to Monterey, I noticed it on both my private and work laptop. Symptoms are exactly as described by @pdgessler:

> [...] the first press of the keyboard shortcut retiles the background windows but does not throw the foreground (focused) window to the new space. The second press of the keyboard shortcut does successfully throw the window. [...]

**Comment by ulope** [comment]
I'm seeing what I assume is the same problem but it's definitely not related to Monterey since I'm still on Big Sur.
In my case it's not always "only" two times. Sometimes it takes 3, 4 tries for the window to "stick" to the new location.

How it behaves:
- Press throw shortcut
- Window jumps to new place
- Window jumps back
- Repeat 1 - 4 times

It started maybe a month or two ago I'd say.

**Comment by AlexW00** [comment]
Same issue. Sometimes even more than twice.

**Comment by okkdev** [comment]
Same issue on my new Macbook Pro M1 Pro
macOS 12.0.1 
Amethyst 0.15.5

**Comment by ulope** [comment]
It's getting worse. I've had cases where it took 5 or 6 tries for a window to stick...

**Comment by rwuwon** [comment]
I saw this issue in macOS 12.0.1 and now 12.1 as of today. I only recall this issue starting with 12.0.1, but can't be sure that I didn't see it with Big Sur. Amethyst 0.15.5 (92) (via Homebrew) - I also reinstalled it, no change.

> It looks like the first press of the keyboard shortcut retiles the background windows but does not throw the foreground (focused) window to the new space. The second press of the keyboard shortcut does successfully throw the window.

Good observation; it does indeed seem to refresh the layout before the window is thrown. The easiest way to see is to "Tall" tile a desktop, and then throw a window to another desktop. The window(s) not thrown will then resize as if the thrown window is already gone.

I mainly use shift-ctrl-option + number (rather than left/right arrows), but did try the other prefix option too (shift-option + number) with no real difference. I noticed that with the second tap, I can have just Ctrl held and it'll still throw, although behaviour can become a bit unpredictable. Behaviour also seems inconsistent depending on whether it's two windows or three on one desktop, as well as whether the window being thrown is the main window or not when in Tall mode. There was also a moment yesterday when after closing Amethyst, I could still throw certain Safari windows to certain desktops around with *only* Ctrl + number. I thought for a moment that macOS had a new keyboard shortcut for this, but it appears it might have been more likely to have been a residual effect from Amethyst.

Also, I don't know if this is related or not, but after upgrading to 12.1, one of my Firefox windows (with pinned tabs) became totally inaccessible, despite about:performance showing the tabs from that window still running. I ended up using OneTab to bookmark all my other windows so I could isolate the remaining zombie tabs and close & reopen them via about:performance. This leads me to suspect that *maybe* there's something going on with macOS's window management, but that's just my speculation. It doesn't really explain why I didn't see this issue with Firefox on 12.0.1, and doesn't explain why some others here have seen the issue with Amethyst since at least Big Sur.

**Comment by veitch123** [comment]
Yep. Likewise. Following this.

**Comment by HanSooloo** [comment]
I will close this, since the new macOS 12.2 update related issue is probably more to the core of this problem.
#1192

**Comment by ulope** [comment]
Is it? I had the problem on macOS 11

**Comment by HanSooloo** [comment]
> Is it? I had the problem on macOS 11 

Mine started appearing after 12.  Others' could be different.
