### ISSUE TITLE
Mouse doesn't follow window when moving windows

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#120]
Options:

1) Call am_focusWindow after moving the window (seems like a lot of overhead since the window is already focused)
2) Add mouse movement logic to screen reflow (more effort and could be situations where this is undesired? can't think of any though)
3) Don't do anything (I think this is undesirable, mainly when moving a window to another screen.  That's a point where I think having the mouse follow the window would be good.)

**Comment by reuben** [comment]
I think this was lost at some point when this was converted to Swift? There's still a lone `focusedWindow.focus()` in `WindowTransitionCoordinator.swapFocusedWindowClockwise` (but not in the other methods), but I think that solution no longer works due to the async nature of the new code. If you add `focusedWindow.focus()` calls to the other window transition methods, the mouse cursor gets updated to the last position before the transition, since the focus() call is sync and happens before the reflow.

I tried calling `Window.currentlyFocused()?.focus()` inside the reflow operation's `completionBlock` but that leads to some weird behavior where the focus is stuck to the currently focused window and you can't change it.

I think there's an additional bug that may be influencing this behavior in `Window.isFocused`. I set some breakpoints and inspected the values during reflow operations, and basically it always returns false. Changing the `isEqual(to: focused)` call to `focused.windowID() == self.windowID()` seems to do the right thing, or at least returns true when I expect it to.

**Comment by ianyh** [comment]
I’ll have to catch up on this later, but can you open a new issue for it?

**Comment by reuben** [comment]
Sure!
