### ISSUE TITLE
Amethyst gets killed in the background

### ISSUE THREAD

**Issue by civiks** [ianyh/Amethyst#1291]
I have searched above and beyond, but I am unable to find why or how this keeps happening.
No matter what you do, Amethyst will automatically get killed and i had to reopen to tile my windows.
I'm on Ventuta Beta 3, and using the latest pre-release version of Amethyst.

**Comment by GreenBattery** [comment]
It perhaps doesn't provide additional diagnostic value, but amethyst 0.16.0 beta is also getting killed on my monterey 12.5.1.

I had assumed it was because I'm using a custom layout as it happens when switching layouts. If I switch to a custom layout, maybe 25% of the time, amethyst dies silently. I have to re-launch it and switch layouts again. Other times it works as expected.

**Comment by luckyluke317** [comment]
It closes on its own and stops working all the time on Ventura beta

**Comment by toiversen** [comment]
Same problem here. I'm on Monterey 12.5.1 and Amethyst 0.16.0
If I have kitty terminal (0.26.2) open, and cmd+Q to kill it, Amethyst is also killed for some reason. None of the other apps I use cause Amethyst to be killed when I exit them.

**Comment by paskn** [comment]
Same here. Amethyst randomly dies without any message about it.
MBP M2, 2022, Ventura 13.4. Amethyst 0.19.0 (103)

**Comment by ianyh** [comment]
Should be fixed in 0.20.0b3.
