### ISSUE TITLE
Create a safe-mode that floats all windows by default

### ISSUE THREAD

**Issue by gitcatt** [ianyh/Amethyst#236]
I had to quit Amethyst bcs I don't have time right now to fiddle around and learn it. Looks _very_ promising.

Meanwhile, I keep discovering app windows that have been full-screened, and it is putting a nasty hurt on my workflow.  :-)

Is there a way to safely reverse everything that amethyst has done?

Please, thank you!

[Trello Card](https://trello.com/c/GQbuHygP/81-amethyst-create-a-safe-mode-that-floats-all-windows-by-default)

**Comment by ifreecarve** [comment]
This functionality appears to be part of v0.11.3

**Comment by ianyh** [comment]
@ifreecarve How do you mean?

**Comment by ifreecarve** [comment]
Maybe I mis-read this feature request as being for the "floating" layout.  Doesn't that layout accomplish what's being discussed here?

**Comment by ianyh** [comment]
This is slightly different, I think. The idea is that when the application launches we wouldn't layout windows without warning/informing the user beforehand, possibly giving the option to disable tiling or maybe even just remember the original positions of the windows so the changes can be reversed. It's not well defined what the actual solution is, but the problem is more about the first time experience rather than choosing a specific layout.

**Comment by ianyh** [comment]
I think this will be covered by having an empty whitelist #655
