### ISSUE TITLE
Focusing a window focuses the entire application

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#245]
This causes annoying problems like focusing a window causing a window on a different screen to come to the forefront.

[Trello Card](https://trello.com/c/nl26k7fa/85-amethyst-focusing-a-window-focuses-the-entire-application)

**Comment by asm89** [comment]
@ianyh I get hit by this a lot. Any pointers on how to fix it? I might give it a shot with some help.

**Comment by corelon** [comment]
I have the same issue. I mainly get it with Google Chrome, as I tend to have multiple windows open as well as multiple profiles (work, personal). Please fix that.

**Comment by ianyh** [comment]
I think the solution is to track which window was last focused on that screen.

**Comment by jacksonfylle** [comment]
When you focus screen 1, amethyst "Focus the main window on the first screen". So if the foreground windows (full screen mode) is not the main window it won't work. What you can do is : "swap-main" the foreground window and "focus-screen-1".

**Comment by max-sixty** [comment]
Are there any workarounds for this? I have just installed Amethyst and it's awesome, but this is frustrating behavior. 

For example, if I have:

- Screen 1: Firefox window beneath an IDE window 
- Screen 2: A number of Firefox windows 

...then switching to any of the firefox windows on Screen 2 will cause the Firefox window on Screen 1 to come to the foreground

I'm using Contexts for switching, which avoids this behavior when Cmd-Tabbing

Thank you!

**Comment by yahooguntu** [comment]
I'm also running into this, but with different behavior. With this arrangement:

* Screen 1: App1 (primary), Firefox, App2
* Screen 2: App3 (primary), Firefox
* Screen 3: Firefox (primary), App4

If a Firefox window was the last window focused on each screen, OR the last window focused on each screen was not a Firefox window, "Focus Screen X" works as expected. Otherwise, "Focus Screen X" will typically focus a Firefox window on the wrong screen, depending on what screen you're trying to jump to.

If you press the "Focus Screen X" shortcut a second time, you'll end up on the correct screen, but only if that screen has a Firefox window.

**Comment by max-sixty** [comment]
I'm a year into using Amethyst and it's really brilliant, thank you @ianyh and all contributors. If you add a GitHub sponsor I'd be happy to sign up. I've recommended it to many others.

This is the one issue that keeps on biting me. It mostly means I can't have more than one screen with a browser window; otherwise when switching to any browser window, all browser windows come to the foreground.

If there's any workaround, please let me know!

**Comment by circld** [comment]
Thanks for an amazing application, @ianyh. I have been using Amethyst for years and it has been a real game-changer for me.

On the subject of this bug, I had no idea these two UX annoyances were related to the same (this) bug:

* Screen 2 & Screen 3 both have browser windows open, and I cannot focus Screen 3 from Screen 1-- using the shortcut to jump to Screen 3 drops me on Screen 2; a second press of the shortcut gets me to Screen 3
* One screen has a full-screen browser window underneath some other application and I would like to look at this application window while I jump focus over to a browser window on another screen-- this causes the browser window on the first screen to jump to the front

Both of these are really unfortunate as they can have a big impact on productivity. Having multiple instances of the same application open is, at least in my experience, an extremely common use case. The former issue has led to accidentally closing the browser window on the wrong screen, and developing a habit of hitting the `focus-sceen-*` shortcuts twice just to be sure I end up where I want to be. The latter issue is particularly problematic since the primary benefit of having multiple screens is to be able compare the content across them; currently, this can be achieved, but only by forcing the user to change their desired usage pattern (e.g., change layouts, concentrate application-specific windows on the same screen, etc).

If you already are aware of all of this, then apologies; my aim was simply to highlight that this one bug is actually rather painful as a user. Where might I see the triaged bug list? Curious to see where this one is in the queue...

**Comment by ianyh** [comment]
This should be fixed as of 0.19.0.
