### ISSUE TITLE
Add keyboard shortcut to toggle focus follows mouse

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#266]
Focus follows mouse is awesome except in some select situations.  Examples are small popup windows, using top bar menus from an app not touching the top bar, working with floating and tiling windows.

We should add the ability to toggle focus follows mouse with a shortcut so we can disable it to perform actions.  Another cool flow might be to disable while holding down a certain key combination (but might be impractical as clicking with control/command/alt keys held down may be troublesome).

[Trello Card](https://trello.com/c/dVLNjqBq/103-amethyst-add-keyboard-shortcut-to-toggle-focus-follows-mouse)

**Comment by Boulet-** [comment]
:+1:

**Comment by ianyh** [comment]
Considering what the shortcut should be for this. Anyone happen to be watching this and have thoughts?

**Comment by ianyh** [comment]
I think I'm going to do `mod2+x` so that it can be done with one hand easily. This obviously favors the right-handed (using right-handed mouse leaves left hand to toggle focus-follows-mouse), but have to have some default, and the default `mod2` already favors handedness (no `ctrl` on the right side of the keyboard). I think the left side of the home row is being used for layout selection, and I want to reserve `z` for commands that "reset" in some way. I already added `mod1+z` that forces relayout, and will probably do `mod2+z` for relaunch if there's still need for it. I apologize to left-handed people for the potentially annoying default.

**Comment by ianyh** [comment]
Oh, and the decision for `mod2` over `mod1` is that `mod1` is usually reserved for things that don't hold a lot of global state. `mod2+t` for example is global tiling.
