### ISSUE TITLE
Can't get amethyst to work on iTerm2 or Terminal windows

### ISSUE THREAD

**Issue by Industrial** [ianyh/Amethyst#304]
It just appears to do nothing with them. If I open some chrome windows it will tile them but nto the terminals

[Trello Card](https://trello.com/c/0vi0tod1/133-amethyst-can-t-get-amethyst-to-work-on-iterm2-or-terminal-windows)

**Comment by ianyh** [comment]
@Industrial Does it work if you force them to tile with `mod1+t`?

**Comment by Industrial** [comment]
It seems to work when I have the option “Float small windows” off.

**Comment by adamryman** [comment]
@Industrial That fixed it for me to.

**Comment by AlejandroMinaya** [comment]
In case that the steps above are not enough, I was able to solve it by changing the default space for my current profile. 
Before it was set to **All Spaces**, and I just had to change it to **Current Space**.
Preferences > Profiles > (Your current profile) > Space: **Current Space**

**System Info:**
- iTerm2 3.3.2
- macOS 10.14.6

**Comment by mlaurel** [comment]
> In case anyone stumbles upon this answer like I did - If iTerm's Desktop assignment from the Dock (right click iTerm on Dock, Assign To) is not set to None, Amethyst ignores iTerm windows.

This worked for me.  Just to reiterate...  
1.  Right click iTerm icon in dock
2.  Options -> Assign To - This Desktop

**Comment by boborbt** [comment]
I have a similar, but not identical problem. With iTerm it tiles correctly the first window (it makes it occupies the full screen), but then it starts acting weirdly. The second window is tiled, but just as if was the first one (it also occupies the full screen, and if I resize to something else it snaps back to that position). Third window tiles at the bottom (which is correct for my tiling scheme, but it is weird because now there is no tile on the right), further windows tile at the bottom as well.

Forcing tiling with alt-shift-T does not solve the problem.

I am on macOS 12.4 and amethyst 0.15.6.

Any idea about how to fix this? Thanks in advance for your help.

**Comment by sfzylad** [comment]
Hello Amethyst folks. I've just installed Amethyst and I love it. However it seems like I have this exact problem. Tried all the suggested solutions and none of them worked.

**System info:**

- Amethyst version: 0.15.6
- MacOS: 12.4
- iTerm2: 3.4.16

Has anyone solved this problem on more recent versions of MacOS and iterm?

**Comment by martin-braun** [comment]
@sfzylad I had the same problem. I wanted to have my hotkey window not be messed up with Amethyst, but my normal windows should tile. On the normal profile, I had to select "No Title Bar" in Window/Style as well, then I had to restart Amethyst.

**Comment by StathisKap** [comment]
I also found that if you enable `Secure Keyboard Entry`, which you can do so from the iTerm2 menu next to the apple logo on the top left corner, then it doesn't work.

The keybinding to enable/disable it is `Option`, `Command`, `S`
