### ISSUE TITLE
Float non-resizable Apps

### ISSUE THREAD

**Issue by milch** [ianyh/Amethyst#377]
Hi,

I'm proposing that an option should be added to float non-resizable apps/windows. As an example, set the layout to something like 'columns' , open a couple of windows and open `System Preferences.app`. Since it's window is non-resizable, it will overlap some of the other windows and the layout will just generally look broken. 

[Trello Card](https://trello.com/c/viMRxBr1/185-amethyst-float-non-resizable-apps)

**Comment by ianyh** [comment]
Yeah. See #380 as another example. I decided to just "tile" them so that you at least get the organization behavior. You also run into this problem with windows that have a minimum size. Xcode is the worst offender I run into regularly. It has a pretty big minimum width. But I definitely want that to tile, even if sometimes windows overlap. It definitely ends up looking pretty kludgey, but I'm not entirely convinced that not tiling them is the right thing to do. I personally usually want System Preferences tiled when I'm using it.

**Comment by ianyh** [comment]
I think I'm going to close this. There are a lot of mechanisms for specifying floating behavior, and I'm not convinced this makes sense in general.
