### ISSUE TITLE
Allow "Switch to desktop [n]" to be bound more flexibly than only ctrl+[n]. 

### ISSUE THREAD

**Issue by bradyt** [ianyh/Amethyst#409]
I have my mod key as capslock, via Seil and Karabiner. I'd like to use capslock+[n] to switch spaces via OSX Preferences, and then have capslock+shift+[n] bound to thow-space-[n]. 

In other words, would like to allow Amethyst to expect the binding to be on cmd+alt+ctrl+[n], rather than the usual ctrl+[n]. 

[Trello Card](https://trello.com/c/XO0nEkjr/200-amethyst-allow-switch-to-desktop-n-to-be-bound-more-flexibly-than-only-ctrl-n)

**Comment by ianyh** [comment]
Yeah, the commands for moving between spaces is pretty high on the list of Things That Are Brittle And Gross. Unfortunately, the full solution requires incorporating some private APIs that I haven't had the time to really dig in to.

**Comment by mitar** [comment]
Could you just allow user to specify which keyboard strokes to use to switch to a space? Just input box to capture keyboard shortcut?

**Comment by ianyh** [comment]
@mitar Yes.

**Comment by ianyh** [comment]
So this... is actually already possible. It's in preferences, and has the command key `throw-space-$n` for the nth space.

**Comment by ianyh** [comment]
Nevermind, this is not the issue I thought it was.

**Comment by MichelDiz** [comment]
I think if it is to standardize the keyboard mapping. I would use the letters just below the numbers. Of course if there is no collision problem with key mapping already used. Instead of leaving the mapping free. But nonetheless leaving customizable mapping possible.

For example. 
Space 11 would be "command + some_cmd + Q" as Space 9 is now "command + some_cmd + 9".

**Comment by x-ji** [comment]
Is this actually done? In Preferences I only see shortcuts for throwing a window to spaces up to 10, but I want to also have shortcuts for throwing to spaces > 10, e.g. 11, 12, as mentioned by @MichelDiz above. MacOS itself already supports defining shortcuts for switching to spaces > 10.

Related issue: https://github.com/ianyh/Amethyst/issues/611, which was closed as a duplicate.

**Comment by x-ji** [comment]
Though I guess the usefulness of such commands mostly depends on this https://github.com/ianyh/Amethyst/issues/934 being fixed first, since > 10 spaces are mostly only useful when there are multiple monitors.

**Comment by hunner** [comment]
MacOS allows up to 16 spaces on a single monitor. I use `ctrl+#` to access spaces 1-10 and `ctrl+opt+#` to access spaces 11-16. I use the Amethyst binding of `ctrl+shift+#` to move windows to spaces 1-10, but there is no way to bind (for example, what I used with yabai and as @x-ji mentioned) `ctrl+shift+opt+#` to move windows to spaces 11-16.

So I think this issue is still valid.

**Comment by ianyh** [comment]
It's feature parity. Supporting beyond 10 is a different function and should have a different issue.
