### ISSUE TITLE
Fails to capture certain kinds of windows (e.g., Firefox)

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#49]
[Trello Card](https://trello.com/c/DWjvEQdD/22-amethyst-fails-to-capture-certain-kinds-of-windows-e-g-firefox)

**Comment by ulope** [comment]
Also happens with PyCharm (IntelliJ based Python IDE)

**Comment by knightjp** [comment]
For me, every single App responds well to the tiling feature, with the exception of Firefox. 
This is odd since at the initial install of Firefox, the windows did respond. But within a couple of hours, it just stopped. Strange. No amount of restarting helped.

**Comment by ianyh** [comment]
So I actually isolated this, finally. It's not the windows that don't respond correctly, it's the application. When the application is launched we try to register some observers on it for things like window creation. For most apps this works fine, but some (e.g., Firefox) aren't responsive initially, so registering the observers fails. Unfortunately, it was doing so _silently_, and once it happened we would fail to get any of its windows not because the windows were weird, but rather that we aren't actually listening for them.

**Comment by ianyh** [comment]
I have a working fix for it. It detects the failure, and then retries with an exponentially backing off delay. It goes up to about a second and a half. My laptop (2017 13" MacBook Pro without Touch Bar) captures Firefox in less than half a second. It's a noticeable lag, but it should be uncommon as it only happens when the application is launched. The tradeoff is almost certainly worth it as I know this is an issue that a lot of users run into.

**Comment by knightjp** [comment]
@ianyh 
The issue with Firefox is an interesting one. After installing Firefox. On the first launch of the app, the windows work perfectly as they should. But then you close the window. When you open a new one, that's it... It does not respond. Open as many windows or as many other apps you wish, the Firefox window floats on top of them taking all the real estate. You can access the other opened windows without minimizing the Firefox one. 
This is basically the thing that I have faced with this issue. 
I can't understand why it works initially and then stops just a few minutes after that.

**Comment by stsievert** [comment]
I ran into this with Firefox Nightly today. Restarting Firefox fixed it.

**Comment by ianyh** [comment]
Wait, restating _Firefox_ fixed it?

**Comment by stsievert** [comment]
Yup, though I never tried restarting Amerhsyt.

**Comment by paanvaannd** [comment]
I'm experiencing some strange behavior with nvALT as well.

nvALT's main window floats by default upon opening. @dhgwilliam mentions in #27 that he would prefer this to be the case, so I'm wondering if this is by design? As far as I know, there is no way to define a white-/black-list of applications for Amethyst, is there?

Anyhow, nvALT's main window does not respond to Amethyst at all initially. It does not tile nor is it select-able through (anti-)clockwise window selection. However, as soon as I open the nvALT preferences pane, both the preference pane window and the main window snap to tiles as expected and are both responsive to Amethyst commands.
