### ISSUE TITLE
Beginner tip: Too many windows, awful layout

### ISSUE THREAD

**Issue by cwagner22** [ianyh/Amethyst#553]
Can someone advise me how one is supposed to use Amethyst (or any Tiling window manager) when more than 4-5 apps/windows are open?

Example:
![screen shot 2017-02-26 at 02 22 23](https://cloud.githubusercontent.com/assets/5314435/23334100/9b48d466-fbca-11e6-9f70-96048e19caab.png)

As you can see it looks terrible and I have no idea why someone would like the windows to look that way. I'm already using Spaces so I don't want to spend my time moving new apps into another Spaces constantly. Do you guys only have a few apps open in each of your Spaces?

I know we can change the tiling layout but I don't think it's gonna fix my issue. I'm using a large monitor so it's even worst on my 13' macbook screen.

Thanks.

**Comment by ianyh** [comment]
Yeah, it's based on the idea of having all of your windows visible at the same time, so if you have a lot of them on the same space it doesn't work very well unless you use the full screen layout. Fullscreen is probably not a good default, though, as it doesn't really give you a sense for what Amethyst is for. 

Is there something that would have helped you here? I've considered having a first launch warning that gives you a chance to undo or something.

**Comment by dm3** [comment]
@cwagner22 - a tiling window manager is just a tool so you need to adjust it to whatever works for you. I'll give an example of my own usage, hopefully it's helpful.

In my case I have 5 spaces each with its own purpose. I only really use the non-fullscreen layout on the space which contains the consoles when I have an external screen attached. The other spaces (Browser, Chat, Documents, Tools) are always in the fullscreen mode.

In the "Console" space I might have up to 10 terminals open at the same time. When I'm on a laptop, the terminals are arranged in fullscreen mode and I navigate them with "forward/backward" movements (I kinda rely on them being arranged according to my own heuristics so that I don't have to fish for the right window every time). When I have external monitors, the current project with 3-4 terminals gets the Tiled layout on the big screen and the other terminals are on the laptop screen with a Fullscreen layout.

I'm only using a basic set of shortcuts:
* switch between tiles on a big screen
* move windows forward/backward inside the space
* send windows between the spaces
* occasionally switch the layout

In my experience having anything but a fullscreen layout on a 13' monitor isn't practical.

**Comment by cwagner22** [comment]
Thanks, that's helpful. I understand how it can be useful for the terminal windows (although I think iTerm has similar windows management features).
But personally I don't like having everything else set to fullscreen. (Particularly when I'm using an external display).
And for the shortcuts Hammerspoon works great for me.

I guess I'll keep it that way for now.
