### ISSUE TITLE
Resize windows in tandem?

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#589]
How do I get Windows to resize in tandem?   For example, with 2 windows side by side, if I make the left window smaller (by dragging the right edge of the window) I want the right window to grow at the same time.

[Trello Card](https://trello.com/c/mXSHzVgD/272-amethyst-resize-windows-in-tandem)

**Comment by ianyh** [comment]
That is not currently implemented. It's also not immediately obvious how it would be implemented as the accessibility APIs only report window frame changes after you finish resizing. There would have to be some sort of polling mechanism in place, and I'm not sure if that can be made performant.

**Comment by ifreecarve** [comment]
If you relax the requirement that the resize happen in real time, this could be covered by #617

**Comment by mwoffenden** [comment]
@ifreecarve Not following you.  Real-time is the only mode that seems to make sense.  I'm picturing resizing the left window (for example) and having the right window grow at the same time.  In real time, in tandem.

**Comment by ifreecarve** [comment]
Maybe I'm missing something here; I'm new to Amethyst although I've been using tiling window managers in X11 for many years.  In the X11 WMs, things happen in realtime -- you drag one window border to resize it, and the surrounding windows move in tandem as you describe.  

In Amethyst, it appears that windows are reorganized based on events like changing focus.  For example, I can resize one window and Amethyst ignores it until I change focus to another window -- at which point the windows return to their original sizes, ignoring what I did with the mouse.  @ianyh suggested that the lack of a real-time API for this in OSX prevents the real-time behavior you're requesting 

What I'm suggesting is that the resizing happens once -- at the moment when you complete the drag operation -- which is what #617 is requesting.

**Comment by mwoffenden** [comment]
I do understand that OSX limitations prevent the "real time" nature of resizing.  However I re-read #617 several times and still don't get the gist of that request.

**Comment by ifreecarve** [comment]
I'm subscribing to `kAXWindowResizedNotification` and I see some realtime resize events.  It might be window-specific though (e.g. resizing terminal windows gives me events each time the window size snaps to a multiple of the character size).  

So, fixing #617 may accomplish this as well after all.

**Comment by ianyh** [comment]
@ifreecarve Interesting. Does it happen with all windows? I'm concerned that Terminal might be weird in this respect because of its unusual window sizing behavior.

**Comment by ifreecarve** [comment]
I'm noticing that if I stop moving the mouse while dragging to resize (even without letting go of the mouse button), the resize event fires.  This happens with Chrome, and a few others.  I haven't tested exhaustively -- just enough to realize that I had to account for this case.

**Comment by ifreecarve** [comment]
Based on the work I've done on #627, I'm not sure how this feature request can be accomplished.

The problem is that in order to do this, you will need to reflow windows as you drag a window border.  But your dragging is triggering `kAXWindowResizedNotification` events -- how you know you need to resize -- and so does reflowing.  The only way I can think of to differentiate between resize events for "the window I'm dragging" and "all other windows" is to only listen for resize notifications while a mouse button is down.  If you reflow while the mouse button is down, you no longer have certainty of which window is being resized by the mouse.  Worse, you have no way to tell whether you're reacting to mouse-based movement or reflow-based movement.

One way to tackle this might be to globally flag a reflow operation in progress.  However, this has every indication of being a choppy operation because you'll have to interrupt the stream of events you're listening to in order to play catch-up on border resizing.  

Hopefully someone can see a solution that I'm missing.

**Comment by ianyh** [comment]
@ifreecarve Would you still consider this unfeasible?

**Comment by ifreecarve** [comment]
I was going to say "yeah, it's unfeasible" but then I figured I should actually experiment first.  I added code to reflow on resize events and here are the results.  **TL;DR it's _almost_ feasible.**

In some cases it works beautifully (if you squint your eyes and ignore the jitter)
![amethyst_589_jitter](https://user-images.githubusercontent.com/583459/32727676-6ed8fcc8-c84b-11e7-8ecb-f749bd4a870c.gif)

But in other cases, it breaks down completely.
![amethyst_589_breakdown](https://user-images.githubusercontent.com/583459/32727681-73ab372a-c84b-11e7-8ca3-d014e284f5eb.gif)

Basically, in order to even attempt this feature you have to assume that resizing a window will *never* cause a window move event.  This doesn't hold; middle layouts and tall widescreen layouts in particular will break this assumption.  When the window moves, it messes up the relation between your mouse cursor and the edge of the window and the behavior becomes very confusing.

You're also causing resize events (via reflow) while causing them, which may explain some of the quirks now.  It's fine to leave this request open (because sometime down the road I'd very much like to have what's described here) but I don't see a way to get it given the OSX APIs available to me as of Nov 2017.

**Comment by ianyh** [comment]
Thanks for testing it @ifreecarve. I don't think this is going to be reasonably possible, and I think the functionality that @ifreecarve has implemented for resizing using the mouse gets far enough given the constraints.
