### ISSUE TITLE
0.11.3b2 Stops tiling frequently

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#592]
It tiles when first relaunched, then stops tiling.  I have to keep relaunching to get it to work. 

Seems to have the most trouble adding new windows.  Removing them is working better.

Ideas?

**Comment by floodedcodeboy** [comment]
It might be helpful to list the other apps you have running and if you have apps running in Apples fullscreen mode. I've had similar issues which I'm detailing and testing.

**Comment by ianyh** [comment]
Yes, what applications are not tiling? Does toggling tiling on the windows work? Does forcing a retile do anything?

**Comment by mwoffenden** [comment]
Not sure what you mean by "toggling tiling".

Tiling only works correctly when Amethyst is first launched.  

After that, for open windows it requires a click away (or two) from the current window to get tiling to work, and even that only occasionally works.  Furthermore, restoring a window from the dock has no effect on tiling, until Amethyst is relaunched again.

**Comment by ianyh** [comment]
Apologies for the confusion. You can toggle whether a window is tiled or floating with <kbd>option</kbd>+<kbd>shift</kbd>+<kbd>t</kbd> by default. Sometimes windows are not automatically captured (see #49) and using this command you can "force" them to be tiled. Forcing a reflow can also sometimes fix timing issues. You can run that command with <kbd>option</kbd>+<kbd>shift</kbd>+<kbd>z</kbd> by default. It just tells the app to rerun the layout algorithm. Let me know if either of those works.

**Comment by tuananh** [comment]
happened to me as well. it takes several seconds for windows to resize.

**Comment by thenayr** [comment]
I'm having the same issue described with version `0.11.3b2`.

For example,  I have chrome and a terminal open,  with chrome focused I hit CMD+N to open a new window,  this window rather than appearing tiled in the existing layout will just appear on top of the already existing chrome window and bypass the tiling.  

Any of the `retiling` commands will fix the issue (option+shift+space, option+shift+z etc), but prior to this opening a new window of chrome would immediately trigger the retiling to occur.

**Comment by zamf** [comment]
Same here

**Comment by ianyh** [comment]
Fixed by #606
