### ISSUE TITLE
Resize panes when a window is resized using the mouse

### ISSUE THREAD

**Issue by bitwiseman** [ianyh/Amethyst#617]
## System

 - **Amethyst version**: 0.11.2
 - **macOS version**: 10.12.5

## What's the Feature Request?
There are keyboard shortcuts to expand or shrink the main pane.  Intuitively, I'd expect that manually resizing the window in the main pane would resize the pane.  The same should happen if I resize the other windows aside from the window in the main pane.  

The difficulty would be in determining what a particular kind of resize means.  Different window resize actions would mean different thing depending on layout, or might be ignored.  Amethyst might need to pop an alert or dialog to allow the user to approve the pane resize.  

[Trello Card](https://trello.com/c/nVSXDGxH/276-amethyst-resize-panes-when-a-window-is-resized-using-the-mouse)

**Comment by ifreecarve** [comment]
I'd love it if this could eventually combined with #82 since the mouse can do precise positioning (vs stepping) in 2 different dimensions at once.

Test cases: 
* What if the window in the main pane can't be resized?  e.g., the system preferences window.  In this case, resizing the secondary pane(s) should accomplish the same thing.  
* What if the layout is something like fullscreen, which doesn't support resizing?  A toast message might be best for communicating this.
* What if the window is maximized and there is no room left for the other windows?  How is that conflict resolved?

**Comment by ifreecarve** [comment]
A clear title might be "Resize panes when a window is resized using the mouse"
