### ISSUE TITLE
fullscreen flash player changing windows order

### ISSUE THREAD

**Issue by Pitometsu** [ianyh/Amethyst#659]
## System

 - **Amethyst version**:

`0.11.4 (52)`

 - **macOS version**:

High Sierra, `10.13.1 (17B48)`

```
Darwin Yuriys-MBP 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64 i386 MacBookPro13,3 Darwin
```
## What's the problem?

When I open full-screen flash player window, it appear on current desktop (not new one, as default on macOS wm). It's not a big deal, but when I close it, windows rearrange a little, and main window not main anymore, so I forced to rearrange them by hands, it's annoying.

## How can it be reproduced?

Open e. g. youtube player in fullscreen (not sure about html5).

## What applications are involved?

Firefox Quantum beta (didn't checked other browsers yet).

## Has anything fixed it, even temporarily?

AFAIK nope

## dotfile (if you have one)

Hm… Didn't know Amethyst even can be configured via dotfile. Where can I read about format?

[Trello Card](https://trello.com/c/5DQ3d0QE/296-amethyst-fullscreen-flash-player-changing-windows-order)

**Comment by ianyh** [comment]
It's possible that flash uses a different fullscreen mechanism than html5 does, and I haven't had any issues with html5. Possibly related to #633

**Comment by Pitometsu** [comment]
iTerm2 work well for me.

**Comment by Pitometsu** [comment]
When use Fullscreen layout, top window keeps top even after opening and closing flash player, but when I return to Tall or Wide layout, it moving to secondary windows.

**Comment by Pitometsu** [comment]
Oh, I guessed it's flash player, but probably I mistaken – and it's html5 player in fullscreen.

**Comment by Pitometsu** [comment]
Well, in every scenario, window which from I open fullscreen player pushing to the end of windows stack (or stay here if already there).

**Comment by ianyh** [comment]
I can no longer reproduce this.

**Comment by leo-labs** [comment]
I could reproduce for html5 video fullscreen in `Firefox 96` on MacOS `10.14.6` (`Darwin redacted 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64`) and Amethyst `0.15.5`:

When firefox is on the main pane and you enter fullscreen e.g. in youtube and then exit, firefox jumps around and is not on the main pane anymore, but some other window. This can be fixed by using MacOS native fullscreen and setting `full-screen-api.macos-native-full-screen` in `about:config` to `true`.  Just leaving this here if someone else has this problem. :beer:
